name: Test deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a # tag=v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
